#!/usr/bin/env bash

CURRENT_DATE=$(date +%Y-%m-%d)
WORKDIR=/disk2/code/groovestomp/self-hosting

LAST_DATE=$(ls /s3/postgres | sort -r | head -n 1)
if [[ ! $(date -d "$LAST_DATE") ]]; then
    LAST_DATE=""
fi

HAS_DIFF=0
if [ ! "$LAST_DATE" ]; then
    HAS_DIFF=1
else
  if [[ $(diff $WORKDIR/docker-compose/volumes/postgres /s3/postgres/$LAST_DATE/) ]]; then
    HAS_DIFF=1
  fi
fi

if [ "0" == "$HAS_DIFF" ]; then
    echo "No diff to backup"
    exit 0
fi

mkdir /s3/postgres/$CURRENT_DATE

pushd $WORKDIR/docker-compose/volumes/postgres
tar cf - . | tar xCf /s3/postgres/$CURRENT_DATE/ -
popd
