#!/usr/bin/env bash

LAST_DATE=$(ls /s3/nextcloud | sort -r | head -n 1)
DATE=$(date +%Y-%m-%d)
WORKDIR=/home/aaron/code/vps

LAST_DATE=$(ls /s3/nextcloud | sort -r | head -n 1)
if [[ ! $(date -d "$LAST_DATE") ]]; then
    LAST_DATE=""
fi

HAS_DIFF=0
if [ ! "$LAST_DATE" ]; then
    HAS_DIFF=1
else
  if diff $WORKDIR/docker-compose/volumes/nextcloud/config /s3/nextcloud/$LAST_DATE/config; then
    HAS_DIFF=1
  elif diff $WORKDIR/docker-compose/volumes/nextcloud/data /s3/nextcloud/$LAST_DATE/data; then
    HAS_DIFF=1
  fi
fi

if [ "0" == "$HAS_DIFF" ]; then
    echo "No diff to backup"
    exit 0
fi

mkdir /s3/nextcloud/$DATE/
set -x
tar cf - $WORKDIR/docker-compose/volumes/nextcloud/config | tar xCf /s3/nextcloud/$DATE/
tar cf - $WORKDIR/docker-compose/volumes/nextcloud/data | tar xCf /s3/nextcloud/$DATE/
set +x
